version: '3.6'

#volumes:
#  pg_project:

services:
  database:
    image: postgres:13
    container_name: mail_service_database
#    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - pg_project:/var/lib/postgresql/data

  root:
    build:
      context: ./
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - database
    environment:
      - APP_PORT=${APP_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}